import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 backdrop-saturate-150 backdrop-blur-md bg-background/80 border-b border-foreground/10">
          <div className="max-w-7xl mx-auto px-4">
            <div className="flex items-center justify-between h-16">
              <div className="font-bold tracking-wide">Kaulu</div>
              <nav aria-label="Main menu">
                <ul className="flex items-center gap-4">
                  <li>
                    <Link className="opacity-80 hover:opacity-100 transition-opacity" href="/">Dashboard</Link>
                  </li>
                  <li>
                    <Link className="opacity-80 hover:opacity-100 transition-opacity" href="#">Reports</Link>
                  </li>
                  <li>
                    <Link className="opacity-80 hover:opacity-100 transition-opacity" href="#">Settings</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
